# Generated by Django 3.1.6 on 2021-02-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryprocessor', '0002_questionmodel_variable_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='variable_fields',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='variable_types',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
