# Generated by Django 3.1.6 on 2021-03-01 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('queryprocessor', '0004_auto_20210207_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='DenyAccessToFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restricted_fields', models.TextField(max_length=10000)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queryprocessor.questionmodel')),
            ],
        ),
    ]
