# Generated by Django 3.1.6 on 2021-02-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_description', models.TextField(max_length=200)),
                ('question_query', models.TextField(max_length=1000)),
                ('variable_fields', models.CharField(max_length=100)),
            ],
        ),
    ]
