# Generated by Django 3.1.6 on 2021-02-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryprocessor', '0003_auto_20210207_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='question_query',
            field=models.TextField(max_length=10000),
        ),
    ]
